SmartGraze/config/routes.rb
Rails.application.routes.draw do
  resources :fence_todevices
  resources :alarmlogs
  resources :polygodetails
  resources :geofences
  resources :schedulers
  get 'dmaps/layout' =>"dmaps#layout"
  post 'getAlarmByDeviceID' =>"alarmlogs#getAlarmByDeviceID"
  get 'SimpleMap' =>"alarmlogs#SimpleMap"
  resources :dmaps
  resources :contacts
  resources :sensors
  get 'AlarmDetail' =>"alarms#AlarmDetail"
  get 'alarms/toAddAlarms' =>"alarms#toAddAlarms"
  get 'alarms/toUpdateAlarms' =>"alarms#toUpdateAlarms"
  post 'alarms/querySensorByDeviceId' =>"alarms#querySensorByDeviceId"
  post 'alarms/addAlarms' =>"alarms#addAlarms"
  get 'map' =>"devices#map"
  post 'getPolygonList' =>"geofences#getPolygonList"
  post 'getPolygonDetail' =>"geofences#getPolygonDetail"
  get 'Tracking' =>"devices#Tracking"
  get 'Playback' =>"devices#Playback"
  get 'DevicesFxtj' =>"devices#DevicesFxtj"
  get 'gettracking' =>"devices#gettracking"
  get 'dmap' =>"devices#dmap"
  get 'Geofences' =>"dmaps#Geofences"
  get 'devices/monitor' =>"devices#monitor"
  get 'monitor' =>"devices#monitor"
  get 'Report' =>"devices#Report"
  get 'OpenAPIV1/GetDeviceDetail' =>"devices#GetDeviceDetail"
  post 'OpenAPIV1/GetDeviceDetail' =>"devices#GetDeviceDetail"
  get 'OpenAPIV1/GetDeviceListResult' =>"devices#GetDeviceListResult"
  post 'OpenAPIV1/GetDeviceListResult' =>"devices#GetDeviceListResult"
  get 'OpenAPIV1/GetDeviceList' =>"devices#GetDeviceListResult"
  post 'OpenAPIV1/GetDeviceList' =>"devices#GetDeviceListResult"
  get 'OpenAPIV1/GetTrackingByUserID' =>"devices#GetTrackingByUserID"
  post 'OpenAPIV1/GetTrackingByUserID' =>"devices#GetTrackingByUserID"
  post 'OpenAPIV1/GetDeviceHistory' =>"sensorlogs#GetAPPDeviceHistory"
  get 'OpenAPIV1/GetDeviceHistory' =>"sensorlogs#GetAPPDeviceHistory"
  post 'OpenAPIV1/GetAddressByLatlng' =>"devices#GetAddressByLatlng"
  get 'OpenAPIV1/GetAddressByLatlng' =>"devices#GetAddressByLatlng"
  get 'devices/layout' =>"devices#layout"
  get 'devices/explore' =>"devices#explore"
  get 'devices/queryLineData' =>"devices#queryLineData"
  get 'devices/alarm' =>"devices#alarmsms"
  post 'devices/:id/update' =>"devices#update"
  post 'devices/getDevices' =>"devices#getDevices"
  get 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'GetDevicesHistory' =>"sensorlogs#GetDevicesHistory"
  resources :devices
  resources :projects
  resources :sensorlogs
  get 'home/index'
  root to: "users#login"
  get 'OpenAPIV1/Login' => 'users#Login'
  post 'OpenAPIV1/Login' => 'users#Login'
  post 'OpenAPIV1' => 'users#Login'
  get 'login' => 'users#login'
  get 'register' => 'users#register'
  post 'register' => 'users#register'
  post '/Service/api/login' => 'users#userCheck'
  post 'login' => 'users#create_login_session'
  delete 'logout' => 'users#logout'
  get 'logout' => 'users#logout'
  resources :alarms
  resources :users
  resources :gateways
  resources :devices
  resources :projects

end

SmartGraze/app/models/polygodetail.rb
class Polygodetail
  include MongoMapper::Document
  key :geofence_id, ObjectId
  key :lat, String
  key :lng, String
  
  belongs_to :geofence   

end

SmartGraze/app/controllers/polygodetails_controller.rb
class PolygodetailsController < ApplicationController
  before_action :set_polygodetail, only: [:show, :edit, :update, :destroy]

  # GET /polygodetails
  # GET /polygodetails.json
  def index
    @polygodetails = Polygodetail.all
  end

  # GET /polygodetails/1
  # GET /polygodetails/1.json
  def show
  end

  # GET /polygodetails/new
  def new
    @polygodetail = Polygodetail.new
  end

  # GET /polygodetails/1/edit
  def edit
  end

  # POST /polygodetails
  # POST /polygodetails.json
  def create
    @polygodetail = Polygodetail.new(polygodetail_params)

    respond_to do |format|
      if @polygodetail.save
        format.html { redirect_to @polygodetail, notice: 'Polygodetail was successfully created.' }
        format.json { render :show, status: :created, location: @polygodetail }
      else
        format.html { render :new }
        format.json { render json: @polygodetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polygodetails/1
  # PATCH/PUT /polygodetails/1.json
  def update
    respond_to do |format|
      if @polygodetail.update(polygodetail_params)
        format.html { redirect_to @polygodetail, notice: 'Polygodetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @polygodetail }
      else
        format.html { render :edit }
        format.json { render json: @polygodetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polygodetails/1
  # DELETE /polygodetails/1.json
  def destroy
    @polygodetail.destroy
    respond_to do |format|
      format.html { redirect_to polygodetails_url, notice: 'Polygodetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_polygodetail
      @polygodetail = Polygodetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def polygodetail_params
      params.require(:polygodetail).permit(:lat, :lng)
    end
end

SmartGraze/app/helpers/polygodetails_helper.rb
module PolygodetailsHelper
end

SmartGraze/app/views/polygodetails/_form.html.erb
<%= form_for(@polygodetail) do |f| %>
  <% if @polygodetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@polygodetail.errors.count, "error") %> prohibited this polygodetail from being saved:</h2>

      <ul>
      <% @polygodetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SmartGraze/app/views/polygodetails/edit.html.erb
<h1>Editing Polygodetail</h1>

<%= render 'form' %>

<%= link_to 'Show', @polygodetail %> |
<%= link_to 'Back', polygodetails_path %>

SmartGraze/app/views/polygodetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Polygodetails</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @polygodetails.each do |polygodetail| %>
      <tr>
        <td><%= polygodetail.lat %></td>
        <td><%= polygodetail.lng %></td>
        <td><%= link_to 'Show', polygodetail %></td>
        <td><%= link_to 'Edit', edit_polygodetail_path(polygodetail) %></td>
        <td><%= link_to 'Destroy', polygodetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Polygodetail', new_polygodetail_path %>

SmartGraze/app/views/polygodetails/new.html.erb
<h1>New Polygodetail</h1>

<%= render 'form' %>

<%= link_to 'Back', polygodetails_path %>

SmartGraze/app/views/polygodetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @polygodetail.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @polygodetail.lng %>
</p>

<%= link_to 'Edit', edit_polygodetail_path(@polygodetail) %> |
<%= link_to 'Back', polygodetails_path %>