SmartEri/config/routes.rb
Rails.application.routes.draw do
  resources :userdevices
  resources :alarmlogs
  resources :schedulers
  get 'dmaps/layout' =>"dmaps#layout"
  resources :dmaps
  resources :contacts
  resources :sensors
  post 'devices/ping' =>"devices#ping"
  get 'devices/ping' =>"devices#ping"
  get 'alarmsms' =>"devices#alarmsms"
  get 'start' =>"users#home"
  get 'lists' =>"devices#lists"
  get 'search' =>"devices#search"
  get 'chart' =>"devices#chart"
  get 'flowinfo' =>"devices#flowinfo"
  get 'panel' =>"devices#panel"
  get 'alarms/toAddAlarms' =>"alarms#toAddAlarms"
  get 'alarmlists' =>"alarms#alarmlogs"
  get 'alarms/toUpdateAlarms' =>"alarms#toUpdateAlarms"
  post 'alarms/querySensorByDeviceId' =>"alarms#querySensorByDeviceId"
  post 'alarms/addAlarms' =>"alarms#addAlarms"
  post 'queryAlarmlogs' =>"alarmlogs#queryAlarmlogs"
  post 'alarms/:id/update' =>"alarms#update"
  get 'dashboard' =>"devices#dashboard"
  get 'devices/monitor' =>"devices#monitor"
  get 'devices/layout' =>"devices#layout"
  get 'devices/explore' =>"devices#explore"
  get 'main' =>"users#main"
  get 'mapdy' =>"users#mapdy"
  get 'devices/queryLineData' =>"devices#queryLineData"
  post 'devices/:id/update' =>"devices#update"
  post 'devices/getDevices' =>"devices#getDevices"
  post 'history' =>"devices#history"
  get 'history' =>"devices#history"
  get 'statistics' =>"devices#statistics"
  get 'province' =>"devices#province"
  get 'point' =>"devices#point"
  get 'city' =>"devices#city"
  get 'trash' =>"devices#trash"
  get 'map' =>"devices#map"
  post 'goHistoryLine' =>"devices#goHistoryLine"
  get 'goHistoryLine' =>"devices#goHistoryLine"
  get 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'querySensorHistoryDatas' =>"sensorlogs#querySensorHistoryDatas"
  post 'querySensorDataDetail' =>"sensors#querySensorDataDetail"
  get 'getSensorsByID' =>"sensors#getSensorsByID"
  post 'getSensor' =>"sensors#getSensor"
  resources :devices
  resources :projects
  resources :sensorlogs
  get 'home/index'
  root to: "users#login"
  get 'login' => 'users#login'
  get 'mapshow' => 'users#mapshow'
  get 'register' => 'users#register'
  post 'register' => 'users#register'
  post 'login' => 'users#create_login_session'
  delete 'logout' => 'users#logout'
  get 'logout' => 'users#logout'
  get '/users/toUpdatePassword' => 'users#toUpdatePassword'
  post '/users/toUpdatePassword' => 'users#toUpdatePassword'
  get 'devicebinding' => 'users#devicebinding'
  post 'users/binding' => 'users#binding'
  post 'users/delbinding' => 'users#delbinding'
  resources :alarms
  resources :users
  resources :gateways
  resources :devices
  resources :projects

end

SmartEri/app/models/device.rb
class Device
  include MongoMapper::Document

  key :project_id, ObjectId
  key :user_id, ObjectId
  key :device_name, String
  key :device_mark, String
  key :device_details, String
  key :device_img, String
  key :create_time, Time
  key :update_time, Float
  key :lon, Float
  key :lat, Float
  key :status, Integer
  key :device_sn, String
  many :sensor
  belongs_to :project   
  belongs_to :user   

end

SmartEri/app/models/devices.rb
class Devices
  include MongoMapper::Document

  key :name, String

end

SmartEri/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
  # GET /devices
  # GET /devices.json
  def ping
    str='故障报警：垃圾桶满溢，位置是未来科技城，请及时处理！'
    if params['name']
       @device= Device.where(device_sn:params['name'].delete(":")).first
       if @device.nil?
        create_time=Time.now
        city="北京市"
        device_name=params['name'].delete(":")
        device_mark=""
        device_details=""
        sn=params['name'].delete(":")
        @device = Device.new(create_time:create_time,device_name:device_name,device_mark:device_mark,device_details:device_details,device_sn:sn,city:city,province:city,type:"1-3")
        @device.save
       end
       if @device
          @sensorO=Sensor.where(:device_id => @device.id,:name => "满溢度").first
          if @sensorO.nil?
            create_time=Time.now
            @sensorO = Sensor.new(device_id:@device.id,time:create_time,value:params[:value],balarm:0,icon:10,interval:0,name:"满溢度",order:7,sensorSign:0,sensorType:1,sensorUnit:"V",tag:"正常",updatetime:create_time.to_i,alarmtime:create_time.to_i)
            @sensorO.save
          end
          @sensorO.update_attributes(value:params[:value])
          create_time=Time.now
          @slog = Sensorlog201704.new(sensor_id:@sensorO.id,time:create_time,value:params[:value],name:"满溢度",tag:"距离",update_time:create_time.to_i)
          @slog.save
          @alarms=Alarmv.where(deviceId:@device.id.to_s,alarmType:"full")
          if @alarms
             for item in @alarms do
                 @con=Contact.find(item.contactId)
                 logger.info @con
                 mobile=@con.mobile
                 pas={}
                 pas["method"] = 'Submit'  
                 pas["account"] = 'cf_zst'  
                 pas["password"] = 'cdc123456'  
                 pas["mobile"] = mobile  
                 pas["content"] = str  
                 uri = URI.parse("http://106.ihuyi.cn/webservice/sms.php?method=Submit")
                 if params[:value].to_i < 27
                  res = Net::HTTP.post_form(uri, pas) 
                 end
                 logger.info "test1"
             end
          end
       end
      
    end
    pas = {}  
    pas["method"] = 'Submit'  
    pas["account"] = 'cf_zst'  
    pas["password"] = 'cdc123456'  
    pas["mobile"] = '13810139056'  
    pas["content"] = str  
    uri = URI.parse("http://106.ihuyi.cn/webservice/sms.php?method=Submit")
    #res = Net::HTTP.post_form(uri, pas) 
    #logger.info res
    respond_to do |format|
      format.json { render :json => {:code =>1,:msg =>"success"} }
    end
  end
  def index
    @devices = Device.all
    current_admin ||=  User.find_by_token(cookies[:token]) if cookies[:token]
    #for de in @devices do
    #    de.update_attributes(user_id:current_admin.id)
      
    #end 
    if current_admin.nil?
        redirect_to root_url, :notice => "已经退出登录"
    end
    name=""
    if params[:name]
       name=params[:name]
    end
    regname = Regexp.new(name)  
    sn=""
    if params[:sn]
       sn=params[:sn]
    end
    regsn = Regexp.new(sn)  
    if params["pid"] and current_admin and current_admin.type ==1
       pid=params["pid"]
       @devices=User.find(pid).device
       @project_name=User.find(pid).name
       @project_id=User.find(pid).id
       @devices=Device.where(:user_id =>pid ,:device_name => regname,:device_sn => regsn)
    end
    if params["pid"] and current_admin and current_admin.type ==2
       @project_name=current_admin.name
       @project_id=current_admin.id.to_s
       @u2ds=Userdevice.where(user_id:current_admin.id.to_s)
       deviceids=[]
       @u2ds.each do |ud|
          deviceids.push(ud.device_id)
       end
       @devices=Device.where(:id.in => deviceids,:device_name => regname,:device_sn => regsn)
    end
    @status=-1
    if params[:status]
     @status=params[:status]
    end
    logger.info "class_1234"
    logger.info @devices.class
  end
  def main
  end
 
  def chart
  end

  def flowinfo
  end

  def search
    page=1
    if params[:page]
      page=params[:page]
    end
    name=""
    if params[:name]
       name=params[:name]
    end
    regname = Regexp.new(name)  
    city=""
    if params[:city]
       city=params[:city]
    end
    regcity = Regexp.new(city)  
    @count=Devices.all.count
    @totolpage=@count/30+1;
    @devices=Devices.where( :device_name => { '$exists'=> true } ).paginate(page:page,per_page:30)
    if name!=""
      @devices=Devices.where( :device_name => regname ).paginate(page:page,per_page:30)
    end
    if city!=""
      @devices=Devices.where( :province => regcity ).paginate(page:page,per_page:30)
    end
  end

  def lists 
    page=1
    if params[:page]
      page=params[:page]
    end
    name=""
    if params[:name]
       name=params[:name]
    end
    regname = Regexp.new(name)  
    type=""
    if params[:type]
       type=params[:type]
    end
    regtype = Regexp.new(type)  
    @count=Devices.all.count
    @totolpage=@count/30+1;
    @devices=Devices.where( :device_name => { '$exists'=> true } ).paginate(page:page,per_page:30)
    if name!=""
      @devices=Devices.where( :device_name => regname ).paginate(page:page,per_page:30)
    end
    if type！=""
      @devices=Devices.where( :type => regtype ).paginate(page:page,per_page:30)
    end
    for item in Devices.all do
       location=item.lon.to_s                                                      
       location+=","                                                                  
       location+=item.lat.to_s                                                     
       params["location"] = location                                                  
       params["key"] = "0b26981dfe81b58acb8b3b96cfb65fe0"                             
       #item.update_attributes(type:"1-1")
       #uri = URI.parse("http://restapi.amap.com/v3/geocode/regeo?key=0b26981dfe81b58acb8b3b96cfb65fe0&location="+location)
       #res = Net::HTTP.post_form(uri, params)                                         
       #logger.info res.body
       #jso=JSON.parse(res.body)
       #if jso["status"] =="1"                                    
        #city=jso["regeocode"]["addressComponent"]["city"] 
        #logger.info city
        #if city.size ==0
          #city=jso["regeocode"]["addressComponent"]["province"] 
        #end
        #item.update_attributes(city:city,province:jso["regeocode"]["addressComponent"]["province"])
       #end
    end
    
  end

  def panel
    page=1
    if params[:page]
      page=params[:page]
    end
    @count=Devices.all.count
    @totolpage=@count/30+1;
    @devices=Devices.all
    
  end
  def province 
  end

  def point
    @ad_p=params[:p1]
    @full_p=params[:p2]
  end

  def trash
     tt = Time.new
     tm=Time.now.to_i
     day=Time.now
     dayt = Time.new(day.year, day.month, day.day)
     tm=dayt.to_i
     @device=Device.find(params[:id])
     @sensorO=Sensor.where(:device_id => @device.id,:name => "今天开门次数累计").first
     if @sensorO.nil?
       @sensorO=Sensor.where(:device_id => @device.id,:name => "今天开门次数").first
     end
     if @sensorO.nil?
       create_time=Time.now
       value=23+rand(1)
       @sensorO = Sensor.new(device_id:@device.id,time:create_time,value:value.to_s,balarm:0,icon:10,interval:0,name:"今天开门次数",order:7,sensorSign:0,sensorType:1,sensorUnit:"V",tag:"正常",updatetime:create_time.to_i,alarmtime:create_time.to_i)
       @sensorO.save
     end
     #if tt.year==2017 && tt.month==2
      # @sensorlog=Sensorlog201702.where(:sensor_id => @sensorO.id,:update_time.gt => tm).sort(:time => :desc)
     #elsif  tt.year==2017 && tt.month==1
      # @sensorlog=Sensorlog201701.where(:sensor_id => @sensorO.id,:update_time.gt => tm).sort(:time => :desc)
     #elsif  tt.year==2017 && tt.month==3
      # @sensorlog=Sensorlog201703.where(:sensor_id => @sensorO.id,:update_time.gt => tm)
     #end
     #if @sensorlog.nil? or @sensorlog.empty? 
      # @device=Device.find("584a4483421aa93765000003")
      # @device=Device.find("57e494ad421aa98d0c000001")
     #end
     #@device=Device.find("57e494ad421aa98d0c000001")
     @sensorM=Sensor.where(:device_id => @device.id,:name => "主蓄电池电压").first
     if @sensorM.nil?
       @sensorM=Sensor.where(:device_id => @device.id,:name => "主电池电压").first
     end
     if @sensorM.nil?
       create_time=Time.now
       value=23+rand(1)
       @sensorM = Sensor.new(device_id:@device.id,time:create_time,value:value.to_s,balarm:0,icon:10,interval:0,name:"主电池电压",order:7,sensorSign:0,sensorType:1,sensorUnit:"V",tag:"正常",updatetime:create_time.to_i,alarmtime:create_time.to_i)
       @sensorM.save
     end
     logger.info @sensorM.value
     @sensorS=Sensor.where(:device_id => @device.id,:name => "副蓄电池电压").first
     if @sensorS.nil?
        @sensorS=Sensor.where(:device_id => @device.id,:name => "副电池电压").first
     end
     if @sensorS.nil?
       create_time=Time.now
       value=23+rand(1)
       @sensorS = Sensor.new(device_id:@device.id,time:create_time,value:value.to_s,balarm:0,icon:10,interval:0,name:"副电池电压",order:7,sensorSign:0,sensorType:1,sensorUnit:"V",tag:"正常",updatetime:create_time.to_i,alarmtime:create_time.to_i)
       @sensorS.save
     end
     @sensorT=Sensor.where(:device_id => @device.id,:name => "温度").first
     if @sensorT.nil?
       create_time=Time.now
       value=0
       @sensorT = Sensor.new(device_id:@device.id,time:create_time,value:value.to_s,balarm:0,icon:10,interval:0,name:"温度",order:7,sensorSign:0,sensorType:1,sensorUnit:"V",tag:"正常",updatetime:create_time.to_i,alarmtime:create_time.to_i)
       @sensorT.save
     end
     @sensorO=Sensor.where(:device_id => @device.id,:name => "今天开门次数累计").first
     if @sensorO.nil?
       @sensorO=Sensor.where(:device_id => @device.id,:name => "今天开门次数").first
     end
     if @sensorO.nil?
       create_time=Time.now
       value=23+rand(1)

SmartEri/app/helpers/devices_helper.rb
module DevicesHelper
end

SmartEri/app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.collection_select :project_id, Project.all, :id, :name %>    
  </div>
  <div class="field">
    <%= f.label :device_name %><br>
    <%= f.text_field :device_name %>
  </div>
  <div class="field">
    <%= f.label :device_mark %><br>
    <%= f.text_field :device_mark %>
  </div>
  <div class="field">
    <%= f.label :device_details %><br>
    <%= f.text_field :device_details %>
  </div>
  <div class="field">
    <%= f.label :device_img %><br>
    <%= f.text_field :device_img %>
  </div>
  <div class="field">
    <%= f.label :create_time %><br>
    <%= f.time_select :create_time %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SmartEri/app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

SmartEri/app/views/devices/goHistoryLine.html.erb
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link rel="icon" href="/images/favicon.ico">
<script src="/js/device/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="/js/device/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/device/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/css/device/jquery.datetimepicker.css">
<link rel="stylesheet" type="text/css" href="/css/device/myIndex.css">
<link rel="stylesheet" type="text/css" href="/css/device/style.min.css">
<script type="text/javascript" src="/js/device/jquery-form.js"></script>
<script type="text/javascript" src="/js/device/navbar.js"></script>
<script type="text/javascript" src="/js/device/jquery.datetimepicker.js"></script>
<script>
var _hmt = _hmt || [];
</script> 
<!DOCTYPE html>
<html>
  <head>
    <base />
    <title>Tlink物联网-监控中心,TLINK物联网-中国最大的物联网开放平台</title>
    <meta name="Keywords" content="TLINK|物联网|智能物联|数字农业|仪器仪表物联网|物联网平台|物联网云服务|物联网开放平台|物联网技术|物联网应用|传感器云平台|环境物联网|能源物联网"  />
    <meta name="Description" content="TLINK物联网是深圳市模拟科技有限公司面向物联网产品的开放平台" />
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<!--
	<link rel="stylesheet" type="text/css" href="styles.css">
	-->
	<script type="text/javascript" src="/js/device/highcharts.js"></script>
	<script type="text/javascript" src="/js/device/exporting.js"></script> 
	
	<script type="text/javascript">  
	var chart; 
	var series;
    var unit;
    var sname;
    var sensorId;
    var queryDate;
    var m;
    var data = [];
	$(document).ready(function() { 
	    var tmpDate = new Date();
	    premonth = tmpDate.getMonth();    //前一月
		month = tmpDate.getMonth() + 1 ;  //当前月
	    
		sensorId=$("#sensorId").val();
        queryDate=$("#queryDate").val();
        m=$("#m").val();
        unit = $("#unit").val();
        sname = "数值";
        
         $("#_pre").html(premonth+"月");
         $("#_cur").html(month+"月");
         $("#_pre").attr("title",premonth+"月份");
         $("#_cur").attr("title",month+"月份");
         $("#_pre").attr("href","/goHistoryLine?sensorId="+sensorId+"&name=&unit="+unit+"&queryDate=3&type=1&url=&m="+premonth);
         $("#_cur").attr("href","/goHistoryLine?sensorId="+sensorId+"&name=&unit="+unit+"&queryDate=4&type=1&url=&m="+month)
        
    	Highcharts.setOptions({  
        	global: {  
            	useUTC: false  
        	}  
    	});  
    	 
    	chart = new Highcharts.Chart({  
        	chart: {  
            	renderTo: 'container',  
            	type: 'spline',  
            	marginRight: 10,  
            	events: {  
                	load: function() {  
                    series = this.series[0];   
                }  
            }  
        },  
        title: {  
            text: ''  
        },  
        xAxis: {  
            type: 'datetime',  
            tickPixelInterval: 150,
        },  
        yAxis: {  
            title: {  
                text: '历史曲线'  
            },  
            plotLines: [{  
                value: 0,  
                width: 1,  
                color: '#808080'  
            }]  
        },  
        tooltip: {  
            formatter: function() {  
                    return  Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) +'<br/>'+  
                    '<b>'+ this.series.name +': </b>'+  
                    Highcharts.numberFormat(this.y, 2)+' ';  
            }  
        },  
        legend: {  
            enabled: false  
        },  
        exporting: {  
            enabled: true  
        },  
        series: [{  
        	turboThreshold: 99999999,
            name: ''+sname,  
            data: (function() {  
                // generate an array of random data  
                $.ajax({
   					type:"post",
   					async: false,
  					url:"/querySensorHistoryDatas?sensorid="+sensorId+"&queryDate="+queryDate+"&m="+m,
   					success:function(sensorData){
   						var jsonObj = sensorData;
   						var sensorsObj=jsonObj.data  
   						var flag = jsonObj.code;
   						var sensorType = $("#sensorType").val();
   						if(flag == 0){
   							var len = sensorsObj.length;
   							for(var i=0;i<len;i++){  
	   							var val = sensorsObj[i].value; 
	   							if('2' == sensorType || '' == sensorType){
	   				   				val = sensorsObj[i].t_switcher;
								}
								
	   							var updateTime = sensorsObj[i].time;
                                                                var date = new Date(sensorsObj[i].time);
	   							//updateTime = updateTime.replace(/-/g,"/");
								//var date = new Date(updateTime);
								 data.push({  
	                        		x: date,  
	                       			y: Number(val)  //初始数据
	                    		});  
                    		}
   						}
					}
                   });
                return data;  
            })()  
        }]  
    });  
});  
</script>  
	
  </head>
  
  <body style="background-color:#fff;">
  <input type="hidden" name="name" id="name" value="æ¸©åº¦"/>
  <input type="hidden" name="unit" id="unit" value="K"/>
  <input type="hidden" name="sensorId" id="sensorId" value="<%=@sensorid%>"/>
  <input type="hidden" name="sensorType" id="sensorType" value="1"/>
  <input type="hidden" name="queryDate" id="queryDate" value="<%=@queryDate%>"/><!--0、小时  1、天  2、月  3、年-->
  <input type="hidden" name="m" id="m" value=""/>
  
  	<p class="history_p">历史数据</p>
  
  <p class="history_cTitle">
     历史曲线
  <span style="margin-left:30px;">Zoom</span>
  <%if @queryDate=="1"%>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=1&type=1&url=" title="最近1小时" class="history_days">1h</a>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=2&type=1&url=" title="最近1天" >1d</a>
  <a href="#"  id="_pre"></a>
  <a href="#"  id="_cur"></a>
  <%elsif @queryDate=="2"%>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=1&type=1&url=" title="最近1小时" >1h</a>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=2&type=1&url=" title="最近1天" class="history_days">1d</a>
  <a href="#"  id="_pre"></a>
  <a href="#"  id="_cur"></a>
  <%elsif @queryDate=="3"%>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=1&type=1&url=" title="最近1小时" >1h</a>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=2&type=1&url=" title="最近1天" >1d</a>
  <a href="#"  id="_pre"  class="history_days"></a>
  <a href="#"  id="_cur"></a>
  <%elsif @queryDate=="4"%>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=1&type=1&url=" title="最近1小时" >1h</a>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=2&type=1&url=" title="最近1天" >1d</a>
  <a href="#"  id="_pre" ></a>
  <a href="#"  id="_cur" class="history_days"></a>
  <%else%>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=1&type=1&url=" title="最近1小时" >1h</a>
  <a href="/goHistoryLine?sensorId=<%=@sensorid%>&unit=K&queryDate=2&type=1&url=" title="最近1天" >1d</a>
  <a href="#"  id="_pre"></a>
  <a href="#"  id="_cur"></a>
  <%end%>
  <!-- <a href="/device/goHistoryLine.htm?sensorId=16262&name=æ¸©åº¦&unit=K&queryDate=3&type=1" title="最近1年" >1y</a> -->
  </p>
  <div class="col-sm-12 history_chart" id="container" style="width: 100%;height: 280px">
  </div>
  
  </body>
</html>