SmartGraze/config/routes.rb
Rails.application.routes.draw do
  resources :fence_todevices
  resources :alarmlogs
  resources :polygodetails
  resources :geofences
  resources :schedulers
  get 'dmaps/layout' =>"dmaps#layout"
  post 'getAlarmByDeviceID' =>"alarmlogs#getAlarmByDeviceID"
  get 'SimpleMap' =>"alarmlogs#SimpleMap"
  resources :dmaps
  resources :contacts
  resources :sensors
  get 'AlarmDetail' =>"alarms#AlarmDetail"
  get 'alarms/toAddAlarms' =>"alarms#toAddAlarms"
  get 'alarms/toUpdateAlarms' =>"alarms#toUpdateAlarms"
  post 'alarms/querySensorByDeviceId' =>"alarms#querySensorByDeviceId"
  post 'alarms/addAlarms' =>"alarms#addAlarms"
  get 'map' =>"devices#map"
  post 'getPolygonList' =>"geofences#getPolygonList"
  post 'getPolygonDetail' =>"geofences#getPolygonDetail"
  get 'Tracking' =>"devices#Tracking"
  get 'Playback' =>"devices#Playback"
  get 'DevicesFxtj' =>"devices#DevicesFxtj"
  get 'gettracking' =>"devices#gettracking"
  get 'dmap' =>"devices#dmap"
  get 'Geofences' =>"dmaps#Geofences"
  get 'devices/monitor' =>"devices#monitor"
  get 'monitor' =>"devices#monitor"
  get 'Report' =>"devices#Report"
  get 'OpenAPIV1/GetDeviceDetail' =>"devices#GetDeviceDetail"
  post 'OpenAPIV1/GetDeviceDetail' =>"devices#GetDeviceDetail"
  get 'OpenAPIV1/GetDeviceListResult' =>"devices#GetDeviceListResult"
  post 'OpenAPIV1/GetDeviceListResult' =>"devices#GetDeviceListResult"
  get 'OpenAPIV1/GetDeviceList' =>"devices#GetDeviceListResult"
  post 'OpenAPIV1/GetDeviceList' =>"devices#GetDeviceListResult"
  get 'OpenAPIV1/GetTrackingByUserID' =>"devices#GetTrackingByUserID"
  post 'OpenAPIV1/GetTrackingByUserID' =>"devices#GetTrackingByUserID"
  post 'OpenAPIV1/GetDeviceHistory' =>"sensorlogs#GetAPPDeviceHistory"
  get 'OpenAPIV1/GetDeviceHistory' =>"sensorlogs#GetAPPDeviceHistory"
  post 'OpenAPIV1/GetAddressByLatlng' =>"devices#GetAddressByLatlng"
  get 'OpenAPIV1/GetAddressByLatlng' =>"devices#GetAddressByLatlng"
  get 'devices/layout' =>"devices#layout"
  get 'devices/explore' =>"devices#explore"
  get 'devices/queryLineData' =>"devices#queryLineData"
  get 'devices/alarm' =>"devices#alarmsms"
  post 'devices/:id/update' =>"devices#update"
  post 'devices/getDevices' =>"devices#getDevices"
  get 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'GetDevicesHistory' =>"sensorlogs#GetDevicesHistory"
  resources :devices
  resources :projects
  resources :sensorlogs
  get 'home/index'
  root to: "users#login"
  get 'OpenAPIV1/Login' => 'users#Login'
  post 'OpenAPIV1/Login' => 'users#Login'
  post 'OpenAPIV1' => 'users#Login'
  get 'login' => 'users#login'
  get 'register' => 'users#register'
  post 'register' => 'users#register'
  post '/Service/api/login' => 'users#userCheck'
  post 'login' => 'users#create_login_session'
  delete 'logout' => 'users#logout'
  get 'logout' => 'users#logout'
  resources :alarms
  resources :users
  resources :gateways
  resources :devices
  resources :projects

end

SmartGraze/app/models/alarmlog.rb
class Alarmlog
  include MongoMapper::Document
  key :device_id, String
  key :name, String
  key :typeID, Integer
  key :createTime, String
  key :latitude, String
  key :longitude, String
  key :deviceTime, String
  key :address, String
  key :note, String

end

SmartGraze/app/controllers/alarmlogs_controller.rb
class AlarmlogsController < ApplicationController
  before_action :set_alarmlog, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /alarmlogs
  # GET /alarmlogs.json
  def index
    @alarmlogs = Alarmlog.all
  end

  # GET /alarmlogs/1
  # GET /alarmlogs/1.json
  def show
  end
 
  def SimpleMap
    @lng=params[:lng]
    @lat=params[:lat]
  end

  # GET /alarmlogs/new
  def new
    @alarmlog = Alarmlog.new
  end

  def getAlarmByDeviceID
    
     @DeviceID=params[:DeviceID]
     logger.info @DeviceID
     @alogs=Alarmlog.where(device_id:@DeviceID)
     respond_to do |format|
       format.json {render :json => {:code =>0,:d => {:reports => @alogs}}}
     end
  end

  # GET /alarmlogs/1/edit
  def edit
  end

  # POST /alarmlogs
  # POST /alarmlogs.json
  def create
    @alarmlog = Alarmlog.new(alarmlog_params)

    respond_to do |format|
      if @alarmlog.save
        format.html { redirect_to @alarmlog, notice: 'Alarmlog was successfully created.' }
        format.json { render :show, status: :created, location: @alarmlog }
      else
        format.html { render :new }
        format.json { render json: @alarmlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarmlogs/1
  # PATCH/PUT /alarmlogs/1.json
  def update
    respond_to do |format|
      if @alarmlog.update(alarmlog_params)
        format.html { redirect_to @alarmlog, notice: 'Alarmlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarmlog }
      else
        format.html { render :edit }
        format.json { render json: @alarmlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarmlogs/1
  # DELETE /alarmlogs/1.json
  def destroy
    @alarmlog.destroy
    respond_to do |format|
      format.html { redirect_to alarmlogs_url, notice: 'Alarmlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarmlog
      @alarmlog = Alarmlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarmlog_params
      params.require(:alarmlog).permit(:name)
    end
end

SmartGraze/app/views/alarmlogs/SimpleMap.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>
	报表中用地图
</title><link rel="stylesheet" href="/css/map/all.css" type="text/css" /><script id="MapSrc" src="http://ditu.google.cn/maps/api/js?sensor=false&language=cn" type="text/javascript"></script>
    <script src="/js/map/language02-zh-cn.js" type="text/javascript"></script>
    <script src="/js/map/SimpleMap.js" type="text/javascript"></script>
    <script src="/js/map/initmap-Google.js" type="text/javascript"></script>
    <script src="/js/map/SimpleMap-Google.js" type="text/javascript"></script>
</head>
<style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
-->
</style>
<body style="overflow:hidden;">
    <form method="post" action="SimpleMap.aspx" id="form1">
<div class="aspNetHidden">
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKLTIwODczMTMzM2RkjmA9HNtM0Fw1jAk8DGovmjA3EUkecjsgN+EP5yERoig=" />
</div>

<div class="aspNetHidden">

	<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="B1E6A8A8" />
	<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="/wEdAAJwHyA+9Rd7qtYAfZZveUe8s3xOGwWdYVd/MA+FcvLrO1VmOpxRTCOCPXzPh7bsY8eJ/zSGznhFCuLxZptaatA4" />
</div>
        <div id="map_canvas" style="height:440px; width:650px;"></div>
        <input name="hidLatLng" type="hidden" id="hidLatLng" value="<%= @lat%>,<%= @lng%>" />
    </form>
</body>
</html>

SmartGraze/app/views/alarmlogs/_form.html.erb
<%= form_for(@alarmlog) do |f| %>
  <% if @alarmlog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alarmlog.errors.count, "error") %> prohibited this alarmlog from being saved:</h2>

      <ul>
      <% @alarmlog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SmartGraze/app/views/alarmlogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alarmlogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarmlogs.each do |alarmlog| %>
      <tr>
        <td><%= alarmlog.name %></td>
        <td><%= link_to 'Show', alarmlog %></td>
        <td><%= link_to 'Edit', edit_alarmlog_path(alarmlog) %></td>
        <td><%= link_to 'Destroy', alarmlog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarmlog', new_alarmlog_path %>

SmartGraze/app/views/alarmlogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alarmlog.name %>
</p>

<%= link_to 'Edit', edit_alarmlog_path(@alarmlog) %> |
<%= link_to 'Back', alarmlogs_path %>