SmartGraze/config/routes.rb
Rails.application.routes.draw do
  resources :fence_todevices
  resources :alarmlogs
  resources :polygodetails
  resources :geofences
  resources :schedulers
  get 'dmaps/layout' =>"dmaps#layout"
  post 'getAlarmByDeviceID' =>"alarmlogs#getAlarmByDeviceID"
  get 'SimpleMap' =>"alarmlogs#SimpleMap"
  resources :dmaps
  resources :contacts
  resources :sensors
  get 'AlarmDetail' =>"alarms#AlarmDetail"
  get 'alarms/toAddAlarms' =>"alarms#toAddAlarms"
  get 'alarms/toUpdateAlarms' =>"alarms#toUpdateAlarms"
  post 'alarms/querySensorByDeviceId' =>"alarms#querySensorByDeviceId"
  post 'alarms/addAlarms' =>"alarms#addAlarms"
  get 'map' =>"devices#map"
  post 'getPolygonList' =>"geofences#getPolygonList"
  post 'getPolygonDetail' =>"geofences#getPolygonDetail"
  get 'Tracking' =>"devices#Tracking"
  get 'Playback' =>"devices#Playback"
  get 'DevicesFxtj' =>"devices#DevicesFxtj"
  get 'gettracking' =>"devices#gettracking"
  get 'dmap' =>"devices#dmap"
  get 'Geofences' =>"dmaps#Geofences"
  get 'devices/monitor' =>"devices#monitor"
  get 'monitor' =>"devices#monitor"
  get 'Report' =>"devices#Report"
  get 'OpenAPIV1/GetDeviceDetail' =>"devices#GetDeviceDetail"
  post 'OpenAPIV1/GetDeviceDetail' =>"devices#GetDeviceDetail"
  get 'OpenAPIV1/GetDeviceListResult' =>"devices#GetDeviceListResult"
  post 'OpenAPIV1/GetDeviceListResult' =>"devices#GetDeviceListResult"
  get 'OpenAPIV1/GetDeviceList' =>"devices#GetDeviceListResult"
  post 'OpenAPIV1/GetDeviceList' =>"devices#GetDeviceListResult"
  get 'OpenAPIV1/GetTrackingByUserID' =>"devices#GetTrackingByUserID"
  post 'OpenAPIV1/GetTrackingByUserID' =>"devices#GetTrackingByUserID"
  post 'OpenAPIV1/GetDeviceHistory' =>"sensorlogs#GetAPPDeviceHistory"
  get 'OpenAPIV1/GetDeviceHistory' =>"sensorlogs#GetAPPDeviceHistory"
  post 'OpenAPIV1/GetAddressByLatlng' =>"devices#GetAddressByLatlng"
  get 'OpenAPIV1/GetAddressByLatlng' =>"devices#GetAddressByLatlng"
  get 'devices/layout' =>"devices#layout"
  get 'devices/explore' =>"devices#explore"
  get 'devices/queryLineData' =>"devices#queryLineData"
  get 'devices/alarm' =>"devices#alarmsms"
  post 'devices/:id/update' =>"devices#update"
  post 'devices/getDevices' =>"devices#getDevices"
  get 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'GetDevicesHistory' =>"sensorlogs#GetDevicesHistory"
  resources :devices
  resources :projects
  resources :sensorlogs
  get 'home/index'
  root to: "users#login"
  get 'OpenAPIV1/Login' => 'users#Login'
  post 'OpenAPIV1/Login' => 'users#Login'
  post 'OpenAPIV1' => 'users#Login'
  get 'login' => 'users#login'
  get 'register' => 'users#register'
  post 'register' => 'users#register'
  post '/Service/api/login' => 'users#userCheck'
  post 'login' => 'users#create_login_session'
  delete 'logout' => 'users#logout'
  get 'logout' => 'users#logout'
  resources :alarms
  resources :users
  resources :gateways
  resources :devices
  resources :projects

end

SmartGraze/app/models/fence_todevice.rb
class FenceTodevice
  include MongoMapper::Document

  key :name, String
  key :device_id, ObjectId
  key :fence_id, ObjectId

end

SmartGraze/app/controllers/fence_todevices_controller.rb
class FenceTodevicesController < ApplicationController
  before_action :set_fence_todevice, only: [:show, :edit, :update, :destroy]

  # GET /fence_todevices
  # GET /fence_todevices.json
  def index
    @fence_todevices = FenceTodevice.all
  end

  # GET /fence_todevices/1
  # GET /fence_todevices/1.json
  def show
  end

  # GET /fence_todevices/new
  def new
    @fence_todevice = FenceTodevice.new
  end

  # GET /fence_todevices/1/edit
  def edit
  end

  # POST /fence_todevices
  # POST /fence_todevices.json
  def create
    @fence_todevice = FenceTodevice.new(fence_todevice_params)

    respond_to do |format|
      if @fence_todevice.save
        format.html { redirect_to @fence_todevice, notice: 'Fence todevice was successfully created.' }
        format.json { render :show, status: :created, location: @fence_todevice }
      else
        format.html { render :new }
        format.json { render json: @fence_todevice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fence_todevices/1
  # PATCH/PUT /fence_todevices/1.json
  def update
    respond_to do |format|
      if @fence_todevice.update(fence_todevice_params)
        format.html { redirect_to @fence_todevice, notice: 'Fence todevice was successfully updated.' }
        format.json { render :show, status: :ok, location: @fence_todevice }
      else
        format.html { render :edit }
        format.json { render json: @fence_todevice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fence_todevices/1
  # DELETE /fence_todevices/1.json
  def destroy
    @fence_todevice.destroy
    respond_to do |format|
      format.html { redirect_to fence_todevices_url, notice: 'Fence todevice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fence_todevice
      @fence_todevice = FenceTodevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fence_todevice_params
      params.require(:fence_todevice).permit(:name)
    end
end

SmartGraze/app/helpers/fence_todevices_helper.rb
module FenceTodevicesHelper
end

SmartGraze/app/views/fence_todevices/_form.html.erb
<%= form_for(@fence_todevice) do |f| %>
  <% if @fence_todevice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fence_todevice.errors.count, "error") %> prohibited this fence_todevice from being saved:</h2>

      <ul>
      <% @fence_todevice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SmartGraze/app/views/fence_todevices/edit.html.erb
<h1>Editing Fence Todevice</h1>

<%= render 'form' %>

<%= link_to 'Show', @fence_todevice %> |
<%= link_to 'Back', fence_todevices_path %>

SmartGraze/app/views/fence_todevices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fence Todevices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fence_todevices.each do |fence_todevice| %>
      <tr>
        <td><%= fence_todevice.name %></td>
        <td><%= link_to 'Show', fence_todevice %></td>
        <td><%= link_to 'Edit', edit_fence_todevice_path(fence_todevice) %></td>
        <td><%= link_to 'Destroy', fence_todevice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fence todevice', new_fence_todevice_path %>

SmartGraze/app/views/fence_todevices/new.html.erb
<h1>New Fence Todevice</h1>

<%= render 'form' %>

<%= link_to 'Back', fence_todevices_path %>

SmartGraze/app/views/fence_todevices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fence_todevice.name %>
</p>

<%= link_to 'Edit', edit_fence_todevice_path(@fence_todevice) %> |
<%= link_to 'Back', fence_todevices_path %>